Hexworks/zircon

src/main/kotlin/org/codetome/zircon/api/graphics/TextImage.kt
src/main/kotlin/org/codetome/zircon/internal/graphics/DefaultTextImage.kt
src/test/kotlin/org/codetome/zircon/internal/graphics/DefaultTextImageTest.kt

Fixed the TextImage so that when you combine them they will autogrow (if needed) to include the second image in its bounds.
fixes issue 
https://github.com/Hexworks/zircon/issues/69

combine with now grows to fit both images in

---

src/test/kotlin/org/codetome/zircon/internal/screen/TerminalScreenTest.kt

yesterday I thought that adding animations to a screen was blocking screen inputs. It turns out this functionality is fine and it was my code that was causing issues. I've written a unit test that proves this behaviour works.

F allow input events with animation

---

zircon.swing/src/main/kotlin/org/codetome/zircon/internal/terminal/SwingTerminal.kt
zircon.swing/src/main/kotlin/org/codetome/zircon/internal/terminal/SwingTerminalFrame.kt

Fixes #77.
This creates a private `Canvas` subclass that invokes an `onPaint` callback.
This also removes `canvas.ignoreRepaint = true`.
I remember reading somewhere in the Swing docs (can't seem to find it now) that it recommended `canvas.setIgnoreRepaint(true)`, but I believe this is only necessary for real-time rendering.
I'm not sure how zircon handles animations, as this library is still new to me, but it definitely doesn't render in real-time when there are no animations playing, so repainting is needed on some platforms.
Edit: Do you know if there's any other importance to ignoring repaint?

Redraw the swing terminal on Canvas.paint().

---

zircon.core/src/main/kotlin/org/hexworks/zircon/internal/component/impl/DefaultComponentContainer.kt

Components were not getting the MOUSE_MOVED event due to a var never
being updated, but used in an if check. The check turned out to be
unnecessary, hence removed.

Fix handleMouseMoved in DefaultComponentContainer

---

README.md

Filled in a couple hyperlinks that are used elsewhere in the document.  Snuck in a typo fix.

revise plurality, add missing code links (#79)

---

zircon.jvm.libgdx/build.gradle
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/renderer/LibgdxRenderer.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/tileset/LibgdxTileset.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/tileset/LibgdxTilesetLoader.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/util/Assets.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/util/LibGDXTileGridFill.kt
zircon.jvm.libgdx/src/test/kotlin/org/hexworks/zircon/LibgdxPlayground.kt

This PR closes issues #167 #173 
Assets are loaded via the `AssetManager`, which provides a safer, less-volatile way to load the textures for rendering. This fixes #167 where the textures were not being found when using LibGDX Zircon in another project.
Publishing and SourceJar sections were added to the `build.gradle` of LibGDX Zircon, which allows the module to be correctly used in an outside project. This change in question solves #173 
This PR now also fixes the rendering of each tile and its backing being off by about 1/2 its height, which fixes the difference between the mouse position and selection of components.

LibGDX Zircon: Loading textures correctly and fixed build.gradle

---

zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/renderer/LibgdxRenderer.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/tileset/LibgdxTileset.kt
zircon.jvm.libgdx/src/test/kotlin/org/hexworks/zircon/LibgdxPlayground.kt

Fixes #177 
This PR renders the tiles starting at the top so that it is more in line with the Swing version and the input handling visually matches the rendering. This commit was co-authored by @wleroux

Tiles render from top to bottom as opposed to the other way around

---

zircon.core/common/src/main/kotlin/org/hexworks/zircon/api/behavior/Selectable.kt
zircon.core/common/src/main/kotlin/org/hexworks/zircon/api/builder/component/ToggleButtonBuilder.kt
zircon.core/common/src/main/kotlin/org/hexworks/zircon/internal/behavior/impl/DefaultSelectable.kt
zircon.core/common/src/main/kotlin/org/hexworks/zircon/internal/component/impl/DefaultToggleButton.kt
zircon.core/jvm/src/test/kotlin/org/hexworks/zircon/internal/component/impl/DefaultToggleButtonTest.kt

The problem was that the builder did not pass its isSelected attribute
over to DefaultToggleButton. In order to make it possible Selectable and
DefaultSelectable had to be modified as well. They now work the same way
as (for example) TextHolder and DefaultTextHolder: Selectable.create()
accepts a boolean argument that is passed over to DefaultSelectable's
constructor which sets its isSelected accordingly through the
selectedProperty.
The fix brought up another problem: the component was not rendered
properly and it looked like as if it wasn't "selected", however, the
internal isSelected attribute held the correct value. A TODO is added to
the DefaultToggleButton where it is supposed to be solved.
Fixes #187

ToggleButtonBuilder ignores the value of isSelected() function

---

zircon.core/common/src/main/kotlin/org/hexworks/zircon/api/builder/component/ModalBuilder.kt

Fix [issue #223 ](https://github.com/Hexworks/zircon/issues/223) by adding the proper comparison operator

Fix issue #223: Component inside modal can't be the same size

---

zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/listeners/ZirconGdxInputListener.kt

Changes the Zircon event associated with the Libgdx keyTyped and keyDown events, from KEY_RELEASED to KEY_TYPED and KEY_PRESSED, respectively.

Fixes #225 : All Libgdx key events processed the same

---

zircon.core/common/src/main/kotlin/org/hexworks/zircon/api/util/TextUtils.kt

While investigating issue #233, I noticed that the default TextArea implementation uses the isPrintableCharacter test to check if the pressed key is printable when no special cases are present. The problem is that there is no special case for the Shift key, so the function tries to determine if the char associated to shift is printable.
The isControlCharacter checks only against the 128 values that an ASCII char can take, but a Char in kotlin is 16bits, so any Char value higher than 126 is considered a printable character. This causes a problem when pressing shift, the char value associated is Char.MAX_VALUE and is considered a printable character and printed to the TextArea.
My fix simply considers any value equals to or higher than 127 to be a control character and therefore not a …

Fix isControlCharacter in TextUtils

---

zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/api/LibgdxApplications.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/application/LibgdxGame.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/renderer/LibgdxRenderer.kt

Attempting to modify LibGDX game to work with the buildApplication() and startApplication() methods to provide the expected result when migrating from the Swing counterparts. Added buildRawApplication() and startRawApplication() for people who want to deal with the creation of the LibGDX game on their own. Fixes issue #222

Modified LibGDX game system to fix compatibility with swing

---

zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/renderer/SwingCanvasRenderer.kt

This should fix the intermittent window size mismatch issue.

Let the Swing JFrame's layout manager decide on the size of the frame.

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfig.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/application/AppConfigBuilder.kt
zircon.jvm.examples/src/main/java/org/hexworks/zircon/examples/game/BorderlessExample.java
zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/renderer/SwingCanvasRenderer.kt

introduce AppConfigBuilder.borderless()
this will create an undecorated window
currently there is tile grid size calculation open when you use just `AppConfigBuilder.fullscreen()`

borderless window / simplified fullscreen #309

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfig.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/application/AppConfigBuilder.kt
zircon.jvm.examples/src/main/java/org/hexworks/zircon/examples/game/IconExample.java
zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/impl/SwingFrame.kt

extend app builder to enable caller to customize applications icon
AppConfig and AppConfiguBuilder now include a null-able string for icon. String has to contain a valid URL to a image. Conversion and loading is done in SwingApplication. Currently I do not like to represent icons URL as string.

Set application icon #297

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/component/CheckBoxBuilder.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/component/CheckBox.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/impl/DefaultCheckBox.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/DefaultCheckBoxRenderer.kt

Implements #332:
* Fixes the 4 wide checkbox when no text is added
* Fixes a bug where not adding text to the checkbox would cause it to not render correctly
* Adds `withLeftAlignedText()` to the CheckBoxBuilder

Checkbox improvements

---

build.gradle.kts
gradle.properties
settings.gradle.kts
zircon.core/build.gradle.kts
zircon.jvm.examples/build.gradle.kts
zircon.jvm.libgdx/build.gradle.kts
zircon.jvm.swing/build.gradle.kts

* The `pluginManagement` block is debatable, however that's probably the easiest way to ensure the version compatibility between Dokka and Dokka's plugins (a slightly worse way would be to use a `buildscript` block)
* The `-modules.html` renaming task probably won't be needed after `1.4.20.2` version
* Unfortunately `kotlinAsJava` format crashes for the `:zircon.core` subproject, please observe https://github.com/Kotlin/dokka/issues/1663 for a fix

Implement docs generation in "Kotlin as Java" format, extract Dokka version to properties

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/DefaultHeaderRenderer.kt
zircon.core/src/commonTest/kotlin/org/hexworks/zircon/CharacterTilesAsString.kt
zircon.core/src/commonTest/kotlin/org/hexworks/zircon/CharacterTilesAsStringTest.kt
zircon.core/src/commonTest/kotlin/org/hexworks/zircon/TestFunctions.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/component/impl/CommonComponentTest.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/component/impl/DefaultHeaderTest.kt

Pretty self-explanatory. It seems like headers should wrap the same way paragraphs do.
I recommend looking at the commits individually; I took deliberate incremental steps towards what you see in the final diff output.
Closes #367.

Update headers to wrap on word, plus test extension functions

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/fragment/impl/table/DefaultTable.kt
zircon.jvm.examples/src/main/kotlin/org/hexworks/zircon/examples/fragments/table/TableExample.kt

A small update to the table fragment: `DefaultTable` now actually updates when the underlying observable list changes. I also extended the `TableExample` accordingly. Have a look:

Table fragment updates on changes

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/ComponentDecorations.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/component/renderer/ComponentDecorationRenderer.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/decoration/BoxDecorationRenderer.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/component/renderer/decoration/BoxDecorationRendererTest.kt

Add horizontal and "vertical" alignment for box titles by adding an additional enum parameter to `box()`. Closes #331.
Note, this is currently stacked on top of my other change, #369, because it uses some helpers I introduced there. I'm going to leave this as a draft until that one gets merged, so that this PR will just contain the one actual commit.

Box title alignment support

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/component/VerticalScrollBarBuilder.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/fragment/ScrollableList.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/impl/BaseScrollBar.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/impl/DefaultVerticalScrollBar.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/VerticalScrollBarRenderer.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/fragment/impl/VerticalScrollableList.kt
zircon.core/src/commonTest/kotlin/org/hexworks/zircon/internal/renderer/TestRenderer.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/fragment/impl/VerticalScrollableListTest.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/renderer/TestRendererTest.kt
zircon.jvm.examples/src/main/kotlin/org/hexworks/zircon/examples/components/ScrollBarExample.kt

This is a possible implementation for the Vertical Scrollable List thing in #372.
I've refactored a lot of the previous work found in [ScrollBarExample.kt](https://github.com/Hexworks/zircon/blob/6c8a084e59cc0acdb2f9b3977ce036a911c97b22/zircon.jvm.examples/src/main/kotlin/org/hexworks/zircon/examples/components/ScrollBarExample.kt) into a reusable Fragment. I also implemented some bug fixes in the scrollbar implementation itself, but I tried to keep these minimal to not pollute the PR, but for example in tiny scroll bars (height 2 for example) the bar doesn't render at all, when it should render with height 1.
I've included a shiny new vaguely-named `TestRenderer` that lets me render the entire component stack and trigger events. It shouldn't _really_ be in this PR, as it's not related to …

Vertical Scrollable List Fragment

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfig.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfigKey.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/application/AppConfigBuilder.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/cobalt/test/MaybeAssert.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/api/application/AppConfigTest.kt

This enables plugin authors to easily set and retrieve configuration options
for the end developer.
Closes #380.

Add custom property support to AppConfig.

---

buildSrc/src/main/kotlin/TestLibs.kt
buildSrc/src/main/kotlin/Versions.kt
zircon.core/build.gradle.kts
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/api/animation/DefaultAnimationRunnerTest.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/internal/uievent/impl/UIEventToComponentDispatcherTest.kt
zircon.jvm.libgdx/build.gradle.kts
zircon.jvm.swing/build.gradle.kts

* Upgrade test library versions.
* Replace initMocks with JUnit rules.
* Use strict stubs.
* Replace "Mockito.`when`" with "whenever".
* Fix a couple tests that were broken.
Closes #384.

Upgrade Mockito and Mockito-Kotlin.

---

zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfig.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/application/AppConfigBuilder.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/resource/TilesetResource.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/tileset/ChainedTilesetLoader.kt
zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/tileset/TilesetLoader.kt
zircon.core/src/jvmTest/kotlin/org/hexworks/zircon/api/tileset/ChainedTilesetLoaderTest.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/renderer/LibgdxRenderer.kt
zircon.jvm.libgdx/src/main/kotlin/org/hexworks/zircon/internal/tileset/LibgdxTilesetLoader.kt
zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/renderer/SwingCanvasRenderer.kt
zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/tileset/SwingTilesetLoader.kt

Closes #386.
Besides unit tests, I can verify in [this commit](https://github.com/nanodeath/zircon-tiled/commit/f1b66a6a2dca1ae9c0baf862bcdfe38755b763bf) that it's actually working in a real example.

Custom tileset loader support.
